# python/verify/action.yml
name: 'NIP-94 Event Verifier'
description: 'Verifies NIP-94 events on Nostr relays'
inputs:
  eventId:
    description: 'Event ID to verify'
    required: true
  relays:
    description: 'Comma-separated list of Nostr relays'
    required: true
outputs:
  found:
    description: 'Whether the event was found (true/false)'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install nostr

    - name: Run verifier
      shell: bash
      env:
        INPUT_EVENTID: ${{ inputs.eventId }}
        INPUT_RELAYS: ${{ inputs.relays }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        # Debug input values
        echo "Event ID: $INPUT_EVENTID"
        echo "Relays: $INPUT_RELAYS"
        
        # Create temporary output file if GITHUB_OUTPUT is not set
        if [ -z "$GITHUB_OUTPUT" ]; then
          export GITHUB_OUTPUT="/tmp/github_output"
          touch $GITHUB_OUTPUT
        fi
        
        python ${{ github.action_path }}/verify_nip94.py
