# python/verify/action.yml
name: 'NIP-94 Event Verifier'
description: 'Verifies NIP-94 events on Nostr relays'
inputs:
  eventId:
    description: 'Event ID to verify'
    required: true
  relays:
    description: 'Comma-separated list of Nostr relays'
    required: true
outputs:
  found:
    description: 'Whether the event was found (true/false)'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install nostr

    - name: Run verifier
      shell: bash
      env:
        INPUT_EVENTID: ${{ inputs.eventId || env.EVENT_ID }}
        INPUT_RELAYS: ${{ inputs.relays }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        # Create output file if it doesn't exist
        touch "$GITHUB_OUTPUT"
        
        EVENT_ID="${INPUT_EVENTID:-$EVENT_ID}"
        
        echo "Event ID: $EVENT_ID"
        echo "Relays: $INPUT_RELAYS"
        
        if [ -z "$EVENT_ID" ]; then
          echo "Error: No event ID provided"
          exit 1
        fi
        
        python ${{ github.action_path }}/verify_nip94.py
        
        # Write both to GITHUB_OUTPUT and GITHUB_ENV
        echo "verify=${verify}" >> $GITHUB_OUTPUT
        # echo "VERIFY=${verify}" >> $GITHUB_ENV

        echo "GITHUB_OUTPUT:"
        echo $GITHUB_OUTPUT
        echo "GITHUB_ENV:"
        echo $GITHUB_ENV
