# python/verify_action.yml
name: 'NIP-94 Event Verifier'
description: 'Verifies NIP-94 events on Nostr relays'
inputs:
  eventId:
    description: 'Event ID to verify'
    required: true
  relays:
    description: 'Comma-separated list of Nostr relays'
    required: true
outputs:
  found:
    description: 'Whether the event was found (true/false)'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install nostr

    - name: Run verifier
      shell: bash
      env:
        INPUT_EVENTID: ${{ inputs.eventId }}
        INPUT_RELAYS: ${{ inputs.relays }}
        GITHUB_OUTPUT: ${{ env.GITHUB_OUTPUT }}
      run: python ${{ github.action_path }}/verify_nip94.py