# python/verify/action.yml
name: 'NIP-94 Event Verifier'
description: 'Verifies NIP-94 events on Nostr relays'
inputs:
  eventId:
    description: 'Event ID to verify'
    required: true
  relays:
    description: 'Comma-separated list of Nostr relays'
    required: true
outputs:
  found:
    description: 'Whether the event was found (true/false)'
runs:
  using: 'composite'
  steps:
    # Skip pythons setup to save time when possible
    - name: Check Python version
      shell: bash
      run: |
        python_version=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "0.0")
        echo "Detected Python version: $python_version"
        if [[ "$python_version" != "3.12" ]]; then
          echo "Python version is not 3.12, setting up Python 3.12"
          echo "SETUP_PYTHON=true" >> $GITHUB_ENV
        else
          echo "Python version is 3.12, skipping setup"
          echo "SETUP_PYTHON=false" >> $GITHUB_ENV
        fi

    - name: Skip python setup
      shell: bash
      run: |
        echo "Using Python 3.12"
      if: env.SETUP_PYTHON == 'true'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
      if: env.SETUP_PYTHON == 'false'

    # skip nostr install if it is already available
    - name: Check if nostr is installed
      shell: bash
      run: |
        python3 -c "import nostr" 2>/dev/null && echo "NOSTR_INSTALLED=true" >> $GITHUB_ENV || echo "NOSTR_INSTALLED=false" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install nostr
      if: env.NOSTR_INSTALLED == 'false'

    - name: Run verifier
      shell: bash
      env:
        INPUT_EVENTID: ${{ inputs.eventId || env.EVENT_ID }}
        INPUT_RELAYS: ${{ inputs.relays }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        # Create output file if it doesn't exist
        touch "$GITHUB_OUTPUT"
        
        EVENT_ID="${INPUT_EVENTID:-$EVENT_ID}"
        
        echo "Event ID: $EVENT_ID"
        echo "Relays: $INPUT_RELAYS"
        
        if [ -z "$EVENT_ID" ]; then
          echo "Error: No event ID provided"
          exit 1
        fi
        
        python3 ${{ github.action_path }}/verify_nip94.py
        
        # Write both to GITHUB_OUTPUT and GITHUB_ENV
        echo "verify=${verify}" >> $GITHUB_OUTPUT
        # echo "VERIFY=${verify}" >> $GITHUB_ENV

        echo "GITHUB_OUTPUT:"
        echo $GITHUB_OUTPUT
        echo "GITHUB_ENV:"
        echo $GITHUB_ENV
