name: Test NIP-94 Publishing
on: [push, pull_request]

jobs:
  test-upload-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create test file
        run: |
          echo "Nostr file metadata test - $(date)" > testfile.txt
      
      # Add step to install dependencies and build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Add step to make the script executable
      - name: Make script executable
        run: chmod +x dist/index.js
      
      - name: Upload to Blossom
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            c03rad0r/upload-blossom-action@using-nsec-argument \
              --host "${{ secrets.HOST }}" \
              --filePath "testfile.txt" \
              --nostrPrivateKey "${{ secrets.NSEC }}"

      - name: Publish NIP-94 Metadata
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          retry_wait_seconds: 10
          polling_interval_seconds: 1
          warning_on_retry: true
          continue_on_error: false
          command: |
            node dist/index.js \
              --relays "wss://relay.damus.io,wss://nos.lol" \
              --url "${{ steps.upload.outputs.blossomUrl }}" \
              --mimeType "text/plain" \
              --fileHash "${{ steps.upload.outputs.blossomHash }}" \
              --content "Test file uploaded via GitHub Actions" \
              --nsec "${{ secrets.NSEC }}" \
              --size "${{ steps.upload.outputs.size }}"
