name: Test NIP-94 Publishing
on: [push, pull_request]

jobs:
  test-upload-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create test file
        run: |
          echo "Nostr file metadata test - $(date)" > testfile.txt
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Make script executable
        run: chmod +x dist/index.js
      
      # Upload steps remain the same
      - name: Upload to Blossom
        id: upload
        continue-on-error: true
        uses: c03rad0r/upload-blossom-action@using-nsec-argument
        with:
          host: ${{ secrets.HOST }}
          filePath: testfile.txt
          nostrPrivateKey: ${{ secrets.NSEC }}

      - name: Upload to Blossom (Retry 1)
        id: upload-retry-1
        if: steps.upload.outcome == 'failure'
        continue-on-error: true
        uses: c03rad0r/upload-blossom-action@using-nsec-argument
        with:
          host: ${{ secrets.HOST }}
          filePath: testfile.txt
          nostrPrivateKey: ${{ secrets.NSEC }}

      - name: Upload to Blossom (Final Attempt)
        id: upload-retry-2
        if: steps.upload-retry-1.outcome == 'failure'
        uses: c03rad0r/upload-blossom-action@using-nsec-argument
        with:
          host: ${{ secrets.HOST }}
          filePath: testfile.txt
          nostrPrivateKey: ${{ secrets.NSEC }}

      # Publish steps with verification
      - name: Publish and Verify NIP-94 Metadata
        id: publish
        continue-on-error: true
        uses: ./
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/,wss://orangesync.tech,wss://damus.io,wss://nostr.land
          url: ${{ steps.upload.outputs.blossomUrl }}
          mimeType: text/plain
          fileHash: ${{ steps.upload.outputs.blossomHash }}
          content: "Test file uploaded via GitHub Actions"
          nsec: ${{ secrets.NSEC }}
          size: ${{ steps.upload.outputs.size }}

      - name: Verify Initial Publication
        if: steps.publish.outputs.eventId
        env:
          VERIFY_MODE: 'true'
          RELAYS: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/,wss://orangesync.tech,wss://damus.io,wss://nostr.land
          EVENT_ID: ${{ steps.publish.outputs.eventId }}
          FILE_HASH: ${{ steps.upload.outputs.blossomHash }}
          EXPECTED_CONTENT: "Test file uploaded via GitHub Actions"
        run: node dist/index.js

      # First retry with verification
      - name: Publish and Verify NIP-94 Metadata (Retry 1)
        id: publish-retry-1
        if: steps.publish.outcome == 'failure'
        continue-on-error: true
        uses: ./
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/,wss://orangesync.tech,wss://damus.io,wss://nostr.land
          url: ${{ steps.upload.outputs.blossomUrl }}
          mimeType: text/plain
          fileHash: ${{ steps.upload.outputs.blossomHash }}
          content: "Test file uploaded via GitHub Actions"
          nsec: ${{ secrets.NSEC }}
          size: ${{ steps.upload.outputs.size }}

      - name: Verify Retry 1
        if: steps.publish-retry-1.outputs.eventId
        env:
          VERIFY_MODE: 'true'
          RELAYS: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/,wss://orangesync.tech,wss://damus.io,wss://nostr.land
          EVENT_ID: ${{ steps.publish-retry-1.outputs.eventId }}
          FILE_HASH: ${{ steps.upload.outputs.blossomHash }}
          EXPECTED_CONTENT: "Test file uploaded via GitHub Actions"
        run: node dist/index.js

      # Final attempt with verification
      - name: Publish and Verify NIP-94 Metadata (Final Attempt)
        id: publish-retry-2
        if: steps.publish-retry-1.outcome == 'failure'
        uses: ./
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/,wss://orangesync.tech,wss://damus.io,wss://nostr.land
          url: ${{ steps.upload.outputs.blossomUrl }}
          mimeType: text/plain
          fileHash: ${{ steps.upload.outputs.blossomHash }}
          content: "Test file uploaded via GitHub Actions"
          nsec: ${{ secrets.NSEC }}
          size: ${{ steps.upload.outputs.size }}

      - name: Final Verification
        if: steps.publish-retry-2.outputs.eventId
        env:
          VERIFY_MODE: 'true'
          RELAYS: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/,wss://orangesync.tech,wss://damus.io,wss://nostr.land
          EVENT_ID: ${{ steps.publish-retry-2.outputs.eventId }}
          FILE_HASH: ${{ steps.upload.outputs.blossomHash }}
          EXPECTED_CONTENT: "Test file uploaded via GitHub Actions"
        run: node dist/index.js

      - name: Check Final Status
        if: always()
        run: |
          if [[ "${{ steps.publish.outcome }}" != "success" && \
                "${{ steps.publish-retry-1.outcome }}" != "success" && \
                "${{ steps.publish-retry-2.outcome }}" != "success" ]]; then
            echo "All publication attempts failed"
            exit 1
          fi
