name: Test NIP-94 Publishing
on: [push, pull_request]

jobs:
  test-upload-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create test file
        run: |
          echo "Nostr file metadata test - $(date)" > testfile.txt
      
      - name: Upload to Blossom
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            upload_output=$(c03rad0r/upload-blossom-action@using-nsec-argument \
              --host "${{ secrets.HOST }}" \
              --filePath "testfile.txt" \
              --nostrPrivateKey "${{ secrets.NSEC }}")
            echo "::set-output name=upload_result::$upload_output"

      - name: Publish NIP-94 Metadata
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            ./dist/index.js \
              --relays "wss://relay.damus.io,wss://nos.lol" \
              --url "${{ steps.upload.outputs.blossomUrl }}" \
              --mimeType "text/plain" \
              --fileHash "${{ steps.upload.outputs.blossomHash }}" \
              --content "Test file uploaded via GitHub Actions" \
              --nsec "${{ secrets.NSEC }}" \
              --size "${{ steps.upload.outputs.size }}"
