name: Test NIP-94 Publishing
on: [push, pull_request]

jobs:
  test-upload-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create test file
        run: |
          echo "Nostr file metadata test - $(date)" > testfile.txt
      
      - name: Upload to Blossom
        id: upload
        uses: c03rad0r/upload-blossom-action@using-nsec-argument
        with:
          host: ${{ vars.HOST }}
          filePath: testfile.txt
          nostrPrivateKey: ${{ secrets.NSEC }}

      - name: Publish NIP-94 Metadata
        uses: ./nostr-publish-file-metadata-action
        with:
          relays: wss://relay.damus.io,wss://nos.lol
          url: ${{ steps.upload.outputs.blossomUrl }}
          mimeType: text/plain
          fileHash: ${{ steps.upload.outputs.blossomHash }}
          content: "Test file uploaded via GitHub Actions"
          nsec: ${{ secrets.NSEC }}
          size: ${{ steps.upload.outputs.size }}
